### ISSUE TITLE
Granny Flats

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/project-ideas#11]
**One sentence description**: 
A Granny Flat is a common term for an Accessory Dwelling Unit (ADU). Currently, it is hard to know if you are able to build an ADU on your property because City Code is different by neighborhood. This tool would help you plot and ADU in your backyard based on known code requirements (parking, impervious cover, distance from other properties, etc).

This idea came of out Code Across 2015.

**Link (more details/brain dump/alpha)**
https://openaustin.hackpad.com/Granny-Flats-Checkin-23-Apr-DIdxVOyhUcQ

**Project Needs (dev/design/resources)**
workflow, mockups, policy expertise

**Status (in progress, pie-in-the-sky)**
lots of good discussions, meetings. Needs a champion to lead and execute vision.

![](https://hackpad-attachments.imgix.net/hackpad.com_DIdxVOyhUcQ_p.362923_1429846400941_Planning%20Canvas.jpg?fit=max&w=882)

**Comment by mscarey** [comment]
I feel like this project existed because of an issue that was current in local politics in 2015, not so much to help people navigate the permit process (which would be only a couple hundred potential users per year). So it doesn't make sense to think of it as a live idea in 2019. I miss 2015 though.

**Comment by mateoclarke** [comment]
yeah 2015 was good @mscarey
