### ISSUE TITLE
Distributed Public Opinion Collection Application Secured by a Block Chain

### ISSUE THREAD

**Issue by johnfilippone** [open-austin/project-ideas#85]
### What problem are we trying to solve?

This will provide a source of public opinion data that you can trust. 
 
In order to get reliable information about public opinion these days you have to look at a ton of different sources because you can't trust any single source.  This is great research practice but the purpose of this project is to create something that can be trusted by virtue of the fact that it is not bent on the assumption that any person or party is trustworthy.  The only thing you have to trust is that the code, which is open source, actually does what we say it does. 

With a decentralized application, the data never goes through a central server, so it cannot be tampered with by me or anyone.  By verifying every vote on a block chain, you can be sure that every time someone answers a question that the vote retains integrity.  

### Who will benefit (directly and indirectly) from this project?

Anyone who cares about knowing the truth.  
The voter/politician accountability relationship.  

### Links to any research/data available/articles

Links here.

### What are the next steps (validation, research, coding, design)? 

1. Hash out some high level questions on how this thing should do what it is meant to do.
2. Design technical infrastructure.
3. Code it up.

The vision:
Phone application.  
No log in (maybe).  Instead it uses your geo-location as the only demographic information about users.  If we allow users to enter their own demographic information, it just allows for more opportunities to spoof.
Simple interface kind of like tinder and other dating apps out there.  A yes or no question appears on the screen, swipe right for yes, left for no, up to skip the question.

The back end will be decentralized and all data will be verified on a block chain.

### What help is needed at this time?

Input on: Should users log in or not?
Input on: Who should write the questions that people submit opinion about?
Poke holes in my idea so that we can think through all the problems.
Infrastructure design.

**Comment by dheerajchand** [comment]
This is a great idea, but it’s going to run into conceptual problems. I worked in public opinion research for a very long time, so what I have to say is informed by that perspective. If it is not germane to what you are trying to accomplish, pardon the spam.1. Surveys, in order to be meaningful, have a lot of structure. Not only is it important how the questions are asked, with what phrasing, with what sequencing (instrument design), but also for how long the survey is active, how the data are collected (fielding methodology), of whom the questions are asked (sampling methodology), etc.  There’s a lot that goes into it. It sounds like what you want to do is focus on the fielding problem, id est, data collection.2. The problems are that without strict controls of timing and sampling, we’ll be building technology that is incomplete, but very good at the one thing that it does.3. To understand why sampling and weighting matter, think about the open polls from media websites. They’re completely meaningless because anyone can vote, possibly multiple times, and the people who are voting are not representative of the population in question. 4. Geolocation is a good proxy for identification, but not perfect. It’s not just the answers that matter, but _who’s_ answering. Without knowing the demographics of who answered, the answer itself is almost meaningless.All that being said, if you want to work on something _like_ this, I know people who’d be interested in supporting it as an open-source venture and who could possibly give it great use.I am traveling for work right now but would you like to talk further when I get back?DheerajOn Jan 1, 2017, at 8:30 PM, John Filippone <notifications@github.com> wrote:What problem are we trying to solve?This will provide a source of public opinion data that you can trust.In order to get reliable information about public opinion these days you have to look at a ton of different sources because you can't trust any single source.  There is some chance that every poll or news source out there is biased or even just lying so you have to look at different sources to dig out small nuggets of actual truth.  The only reason to trust one source or another is their name (Gallup, CNN etc.) and that is very poor reason to trust something.With a decentralized application, the data never goes through a central server, so it cannot be tampered with by me or anyone.  By verifying every vote on a block chain, you can be sure that every time someone answers a question that the vote retains integrity.
Who will benefit (directly and indirectly) from this project?Anyone who cares about knowing the truth.
The voter/politician accountability relationship.
Links to any research/data available/articlesLinks here.
What are the next steps (validation, research, coding, design)?

Hash out some high level questions on how this thing should do what it is meant to do.
Design technical infrastructure.
Code it up.
The vision:
Phone application.
No log in (maybe).  Instead it uses your geo-location as the only demographic information about users.  If we allow users to enter their own demographic information, it just allows for more opportunities to spoof.
Simple interface kind of like tinder and other dating apps out there.  A yes or no question appears on the screen, swipe right for yes, left for no, up to skip the question.The back end will be decentralized and all data will be verified on a block chain.
What help is needed at this time?Input on: Should users log in or not?
Input on: Who should write the questions that people submit opinion about?
Infrastructure design.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/open-austin/project-ideas","title":"open-austin/project-ideas","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/open-austin/project-ideas" class="">https://github.com/open-austin/project-ideas</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Distributed Public Opinion Collection Application Secured by a Block Chain (#85)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/open-austin/project-ideas/issues/85" class="">https://github.com/open-austin/project-ideas/issues/85</a>"}}}

**Comment by johnfilippone** [comment]
@dheerajchand Thanks for the perspective, I would like to talk with your further on this if you are up for it.  I'm also interested to get in touch with anyone you think would want to help out.

In response to your comments:
Addressing questions:  In my current vision, questions must be yes or no questions, must be very specific, must be absent of any assumptions, must be absent of any pre-loading information.  
Example questions:
Do you think the federal government should play a role in health care?
Do you think local government should play a role in health care?
Do you think that possession of marijuana should be completely legal?
Do you believe that possession of marijuana should be punishable only above a certain quantity?
Do you think that a citizen who is legally open carrying a weapon should be allowed to refuse to show open carry license credentials to a police officer in public?
Do you think the legal drinking age should be anything other than 21?
Do you think the legal driving age should be anything other than 16?

Aderessing timing:  With this system it is possible to track the exact time that someone answers a question. 

Addressing sampling:  The goal with this project is to create a polling system that is so very easy to use and so very reliable and so trust-less that it is used by almost everyone.  Not unlike the way Facebook is used by almost everyone.  The sample will never be perfect but the idea is to overcome misrepresented samples by reaching some critical mass of voters.  Questions will probably be categorized and any given person will be more likely to answer all the questions in some categories over others. Maybe this can be overcome by not allowing users to access questions by catagories, instead they just get a random stream.  You can skip but the question will just go back into the random selection pool until you answer it.

New development:  Maybe users should be allowed to submit questions of their own.  Then the questions will be vetted before they are added to the pool.  Maybe I can hire a law student to do that something.  Someone who I can meet in person, vet, and trust to do a good job.

**Comment by johnfilippone** [comment]
I will be at the meetup this Saurday 1/7/17 if anyone is interested in talking about this more.

**Comment by dheerajchand** [comment]
More than happy to continue the conversation, but I am currently traveling for work through the end of January, so my ability to respond is mitigated.

From the instrument design perspective, binary questions are not particularly helpful, which we can go over in person when I get back. The problem with them is that they are not granular enough to provide useful and actionable information to guide decision making.

So, we should build this, but with more refinements.

TTYS!

-dx

**Comment by johnfilippone** [comment]
To expand on the vision here and in response to concerns about usefulness of the binary questions:

Perhaps it should not be used to guide decision making necessarily if that is the case.  I think that having simple yes/no questions is key to getting people to use it.  Perhaps the most important function of an application I believe is to act as a catalyst for political discussion and increased interaction between constituents and politicians.  There should be some way of comparing opinion of a particular geographical region to the actions of politicians who represent them. I'm not sure what the best way to do this is yet.  This makes things more personal, making it more fun to use.  All of a sudden politicians can have stats and following politicians becomes easier, people will start to talk about them.  Perhaps even some questions should be more personally charged for the same reason; something like:  Do you think Paul Ryan is smart?  Questions like this may increase user activity but are kind of almost gossipy and not in the spirit of this project.  I much more like the idea of giving politicians states based on their actions.  That is a hard problem that I would love to hear someone contribute some ideas about.

**Comment by dheerajchand** [comment]
I want to make it very clear that I am not trying to say that your idea is bad, but, in fact, the opposite: your idea is _good_. I think that we can refine this into being a very, very valuable data collection tool that can be used for online surveys, which are looking to be the last viable means of survey methodology.

This is a hard problem, for sure. Defo looking forward to discussing upon return.

-dx

**Comment by johnfilippone** [comment]
That is understood.  I'm trying not to come off as defensive over the idea.  I think it has a ways to go and should change and evolve until it is ready to be implemented.

**Comment by werdnanoslen** [comment]
Hi @johnfilippone, how are you doing on this project idea? Anything I can help you with to move forward?

**Comment by johnfilippone** [comment]
You can help by sharing your thoughts on the following thoughts of mine:

How can we generate a large amount of quality, simple, and unbiased questions?  How many do we need and at what rate should they be generated?  Who should make them? Perhaps a system can be devised where users can reliably do this themselves.  This is the biggest hurtle in my opinion at the moment. 

Once this data is available, what we do not want is for someone to be able to use it and site our data in a way that actually misrepresents the data or plainly lies about it.  A platform like data.world seems to offer a possible solution to this through their transparent approach to data sharing. 



In general the plan is looking like this at the moment:
Phone application.  No log in.  Demographic data is based on the reset geolocation of the MAC of the device (even if someone is traveling they would still be voting in their home district, or technically wherever they last reset the phone).  Questions are yes or no.  Database tables for each question basically have two non trivial columns: district of voter and yes/no vote.  UI is basically like tinder but no login, you just open it, you allow it to decide what district you are voting in and start seeing questions.  Swipe right/left for yes/no.  Possible second page of app for checking out statistics but that is a whole other part of the system that I have not thought about much. I am mostly concerned with getting great data and setting it loose in a secure and transparent way.

**Comment by werdnanoslen** [comment]
1. Research design (including surveys) requires substantial knowledge to control bias and describe its effects. There's no such thing as an unbiased question, because people don't all infer the same information. So I don't think there can be an automated solution to generating a question that effectively controls for bias other than automatically pulling from an expert source. At the same time, sampling bias and response rate are also factors to the truthiness of a study. For appropriately formulated studies, you'll need a source of research expertise. That will probably drive your other questions in part one.

2. The classic question. In this case it's fairly light on interaction and data transfer so perhaps integration with another application would be useful.

3. If someone has access to the data, there's nothing stopping them from doing something with it you don't want other than legal action. You'd probably have to either accept that or close access to the data, which is probably the last thing you'd want for a decentralized database.

**Comment by johnfilippone** [comment]
1.  Perhaps then this project should not aim to produce 'unbiased' questions but instead perfect accessibility of transparent data.  

Maybe users can generate questions with some strict guidelines.  In a system where distributed means trustless, it would make sense to also make question generation distributed as well, only audited by an algorithm, no people.  If all questions go through a single party of any form, it defeats the spirit of the system. 

Possible question constraints:  must be yes/no questions.  must be under x characters.  must give a relevant category for the question.  These types of constraints can be checked by a computer with some slightly sophisticated language analysis.  Subtle bias will be there but an algorithm can probably cull out ridiculous questions.  


3. It is probably true that the best we can do to stop misuse of the data is make it so easy to access and so transparent that anyone trying to spoof it would be easily debunked.

**Comment by werdnanoslen** [comment]
Yes, I think a blockchain model for creating a circle of trust on a particular type of data (survey data) might be useful for folks who want distributed confidence in the authenticity of the data. Blockchains are not particularly accessible, though, for folks who aren't familiar with what they are and how they work. So perhaps one aspect of this project is making the tech accessible to particular groups of people.

What exactly would the expected outcomes be of an algorithmic audit? That the questions added to the system are trusted to correspond with its response data?

I am interested to see what a plain text algorithm would be to guarantee that a question doesn't have bias. For example, how would you measure ridiculousness?

What are some examples of highly accessible and transparent data that others can check easily to verify a claim? And what is more important for the problem, access to data or access to inferences? For example, [Google has a fact checker](https://blog.google/products/search/fact-check-now-available-google-search-and-news-around-world/) built on ClaimReview schema in certain results of searches including claims like ["27 million people enslaved"](https://www.google.com/search?q=27+million+people+enslaved&oq=27+million+people+enslaved&aqs=chrome..69i57.2928j0j4&client=ubuntu&sourceid=chrome&ie=UTF-8). This gives Google users access to inferences and links to data, but most Googlers want to look at the raw data format. Whereas the programmers care more about the data than the inference, because they want to build things. Who are your users for this project?

**Comment by johnfilippone** [comment]
You're right; there needs to be a PR campaign of sorts to educate the public on block chain.  

Algorithmic audit would just make sure questions are yes/no questions and that they are comprehensible mostly.  We also want to make sure we can sort things on the back end by category so algorithm needs to check for relevance to the topic as well.  Perhaps we cannot eliminate bias algorithmicly because it is hard to do that even by hand.  But eliminating questions like "Is Iraq ugly?" or "Is the Taliban over weight?" might be a challenge.  Those are ridiculous.   Maybe the first is easy because you can analyze that "ugly" does not apply to a Place or at least we don't care for those types of questions.  The second might be eliminated because of the keyword "over weight?" I'm not sure.  These are algorithmic problems and I believe they can be solved with proper language analysis; probably some ML techniques much more sophisticated than what I described.

I think for the spirit of this thing to prevail, it is necessary to make easily accessible interfaces available AND properly documented and open data available for review.  For example, if there is a statistic shown on one of our interfaces that says "Average income of this district is $40,000," there ought to be a link to the database and it's documentation i.e. how was the average of each district calculated? Were homeless people included? Where people under 18 included? Under 21? Students? etc.  What were the collection methods and time period? A smart person can do all the calculations themselves based on the documentation of how things were calculated and the raw data that is backed by the block chain.

**Comment by werdnanoslen** [comment]
The thing with ML though is that output is almost always expressed with a degree if confidence. So you'd have to train the algorithm with some smaller data and then it will yield it's own answers on test data with x% certainty based on what you trained it on. So even then you'd need to either trust in it's confidence and set a threshold for it to be accepted by the system as true, or you'd again need a human to verify which breaks the complete trust a blockchain seeks to provide. I think you're close to specifying a data scheme, which would be a good first step toward your overall goal. How about for the first part of this project you set up a human-centered set of instructions for this process? Then you can go step by step and find ways to automate it to some degree of confidence. And along the way you'll be learning how accessible this system would be as a human-centered or blockchain tech-related method.

**Comment by werdnanoslen** [comment]
This might be totally unrelated,but #100 includes some idea of using blockchains for personal health information.

**Comment by werdnanoslen** [comment]
Hi @johnfilippone how's it going? Do you need any help on this project?

**Comment by MalikKillian** [comment]
One thing I see as a big challenge here is user Authentication. We'd want to make sure there is only one account per person and preferably ensure that any demographic information is accurate.  If we can't confirm that a person is using only one account then this is really no more accurate then the average web poll.  So far the best authentication method of this type I've seen is through PayPal APIs. They have an API that can confirm an account is verified, This means the person has provided either a bank account, credit card, or social security number.

**Comment by mscarey** [comment]
Looks like this discussion ended without reaching an actionable project plan, so I'll close this issue.
